### ISSUE TITLE
molly.im IPv6 support

### ISSUE THREAD

**Issue by Mynacol** [mollyim/mollyim.github.io#6]
I noticed that my F-Droid client does only use IPv4 to connect to the molly.im F-Droid repo. After digging around, I learned you use github pages and that they quite recently [added support for IPv6](https://github.blog/changelog/2021-09-30-enabling-ipv6-support-for-github-pages/)

Their updated [github pages doc](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) now recommends setting four AAAA records (to follow your scheme by not using a CNAME redirect)

Thanks!

**Comment by valldrac** [comment]
I just added the missing AAAA records. Thanks for reporting it.
